name: Build feynman's pr

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm install
          npm run build; node build-sw

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: feynman.avinashkanaujiya.me
